Start adding firmware update stuff
Start by stubbing out OOB BIOS update paths, and adding an in-band IPMI
firmware update path.

diff --git a/core/barclamps/ipmi.yml b/core/barclamps/ipmi.yml
--- a/core/barclamps/ipmi.yml
+++ b/core/barclamps/ipmi.yml
@@ -308,10 +308,110 @@ roles:
                         - ipmi-crossed-access-channels
                         - ipmi-immutable-rootname
                         - ipmi-immutable-root
+  - name: ipmi-flash
+    jig: script
+    requires:
+      - ipmi-discover
+    wants-attribs:
+      - ipmi-enable
+      - ipmi-firmware-rev
+      - ipmi-device-id
+      - ipmi-device-rev
+      - ipmi-mfgr-id
+      - ipmi-product-id
+      - provisioner-webservers
+    attribs:
+      - name: ipmi-firmware-list
+        description: "List of firmware updates available"
+        map: 'ipmi/firmware_updates'
+        schema:
+          type: seq
+          sequence:
+            - type: map
+              mapping:
+                "ipmi-firmware-rev":
+                  type: str
+                  required: true
+                "ipmi-device-id":
+                  type: str
+                  required: true
+                "ipmi-device-rev":
+                  type: str
+                  required: false
+                "ipmi-mfgr-id":
+                  type: str
+                  required: true
+                "ipmi-product-id":
+                  type: str
+                  required: true
+                "package-source":
+                  type: str
+                  required: false
+                "package":
+                  type: str
+                  required: true
+                "package-sha256sum":
+                  type: str
+                  required: true
+                "script":
+                  type: str
+                  required: true
+        default:
+          - package: 'iDRAC-with-Lifecycle-Controller_Firmware_W719V_LN_2.32.31.30_A00.BIN'
+            package-sha256sum: 'e1d287f8a0e098cd4bbe25e60519c4765bbcf28a52f24157d73a81cf8011456e'
+            package-source: 'http://downloads.dell.com/FOLDER03799556M/1/iDRAC-with-Lifecycle-Controller_Firmware_W719V_LN_2.32.31.30_A00.BIN'
+            ipmi-mfgr-id: "674"
+            ipmi-product-id: "256 (0x0100)"
+            ipmi-device-id: "32"
+            ipmi-device-rev: "1"
+            ipmi-firmware-rev: "2.32"
+            script: |
+              #!/usr/bin/env bash
+              "$package" -q -r
+              case $? in
+                  0)  # No reboot required.
+                      exit 0;;
+                  1)  # The update failed.
+                      exit 1;;
+                  2)  # Update suceeded, system needs a reboot.
+                      reboot; sleep 600;;
+                  3)  # Dependency error, system already up to date
+                      echo "System up to date, but should have been caught by pre-version check"
+                      exit 0;;
+                  4|5) # Update not applicable to the system
+                      echo "Update $package not applicable to this system, but not caught by qualification checking"
+                      exit 1;;
+                  6) # System is automatically rebooting
+                     sleep 600;;
+                  *) # Update package is corrupt or Something Weird happened.
+                     echo "Unexpected exit status $?, something weird happened"
+                     exit 1;;
+              esac
+          - package: 'SMT_316.zip'
+            package-sha256sum: '07e82a8a2c83cea9cf567297b5cc87334f602bd919fa43ad070bad55e3cfe775'
+            package-source: 'http://www.supermicro.com/about/policies/disclaimer.cfm?url=/support/resources/getfile.aspx?ID=2815'
+            ipmi-mfgr-id: '47488'
+            ipmi-device-id: '32'
+            ipmi-device-rev: '1'
+            ipmi-product-id: '2566 (0x0a06)'
+            ipmi-firmware-rev: '3.16'
+            script: |
+              #!/usr/bin/env bash
+              unzip -j "$package" 'SMT_316.bin' 'Linux 1.15/lUpdate' 'Linux 1.15/unload_ipmi_driver.sh'
+              chmod 755 lUpdate unload_ipmi_driver.sh
+              ./unload_ipmi_driver.sh
+              if ! ./lUpdate -f SMT_316.bin -i kcs -r y; then
+                  echo "Update failed!"
+                  exit 1
+              fi
+              echo "Update succeeded.  Will reboot after IPMI controller reboots"
+              sleep 60
+              reboot
+
   - name: ipmi-configure
     jig: chef
     requires:
-      - ipmi-discover
+      - ipmi-flash
       - rebar-managed-node
     wants-attribs:
       - ipmi-enable
