Make the provisioner even more node UUID vs. node name agnostic

diff --git a/containers/provisioner/update-nodes/templates/centos-7.ks.tmpl b/containers/provisioner/update-nodes/templates/centos-7.ks.tmpl
--- a/containers/provisioner/update-nodes/templates/centos-7.ks.tmpl
+++ b/containers/provisioner/update-nodes/templates/centos-7.ks.tmpl
@@ -49,13 +49,6 @@ export PS4='${BASH_SOURCE}@${LINENO}(${FUNCNAME[0]}): '
 export REBAR_ENDPOINT="{{.CommandURL}}"
 export REBAR_KEY="{{.Param "rebar-machine_key"}}"
 echo "$REBAR_KEY" >/etc/rebar.install.key
-export HOSTNAME="{{.Machine.Name}}"
-if [ -f /etc/sysconfig/network ] ; then
-      sed -i -e "s/HOSTNAME=.*/HOSTNAME=${HOSTNAME}/" /etc/sysconfig/network
-fi
-echo "${HOSTNAME#*.}" >/etc/domainname
-echo "$HOSTNAME" >/etc/hostname
-hostname "$HOSTNAME"
 
 # Use the install repo from the provisioner for local package installation
 cat >/etc/yum.repos.d/00-rebar-base.repo <<EOF
@@ -79,6 +72,25 @@ sed -i '/^enabled/ s/1/0/' /etc/yum/pluginconf.d/fastestmirror.conf
 
 # Install ntpdate
 yum -y install ntpdate jq
+
+node_json="$(rebar nodes show "{{.Machine.Name}}")" && \
+    HOSTNAME="$(jq -r '.name' <<<"$node_json")" && \
+    REBAR_UUID="$(jq -r '.uuid' <<< "$node_json")" 
+
+if ! [[ $HOSTNAME && $HOSTNAME != null && $REBAR_UUID && $REBAR_UUID != null ]]; then
+    echo "Unable to configure hostname and rebar uuid!"
+    sleep 9000
+    exit 1
+fi
+if [ -f /etc/sysconfig/network ] ; then
+      sed -i -e "s/HOSTNAME=.*/HOSTNAME=${HOSTNAME}/" /etc/sysconfig/network
+fi
+echo "${HOSTNAME#*.}" >/etc/domainname
+echo "$HOSTNAME" >/etc/hostname
+hostname "$HOSTNAME"
+export HOSTNAME
+
+echo "$REBAR_UUID" > /etc/rebar-uuid
 
 # Make sure we can install gems
 cat >/etc/gemrc <<EOF
@@ -145,8 +157,8 @@ chkconfig NetworkManager off || :
 chkconfig network on || :
 rm /etc/yum.repos.d/rebar-epel.repo
 
-rebar nodes update "$HOSTNAME" '{"bootenv": "local"}'
-while [[ $(rebar nodes get "$HOSTNAME" attrib provisioner-active-bootstate |jq -r '.value') != local ]]; do
+rebar nodes update "$REBAR_UUID" '{"bootenv": "local"}'
+while [[ $(rebar nodes get "$REBAR_UUID" attrib provisioner-active-bootstate |jq -r '.value') != local ]]; do
     sleep 1
 done
 
diff --git a/containers/provisioner/update-nodes/templates/net-post-install.sh.tmpl b/containers/provisioner/update-nodes/templates/net-post-install.sh.tmpl
--- a/containers/provisioner/update-nodes/templates/net-post-install.sh.tmpl
+++ b/containers/provisioner/update-nodes/templates/net-post-install.sh.tmpl
@@ -145,17 +145,28 @@ apt-get -y --force-yes install ntpdate jq curl
 export REBAR_ENDPOINT="{{.CommandURL}}"
 export REBAR_KEY="{{.Param "rebar-machine_key"}}"
 echo "$REBAR_KEY" >/etc/rebar.install.key
-export HOSTNAME="{{.Machine.Name}}"
+
+node_json="$(rebar nodes show "{{.Machine.Name}}")" && \
+    HOSTNAME="$(jq -r '.name' <<<"$node_json")" && \
+    REBAR_UUID="$(jq -r '.uuid' <<< "$node_json")" 
+
+if ! [[ $HOSTNAME && $HOSTNAME != null && $REBAR_UUID && $REBAR_UUID != null ]]; then
+    echo "Unable to configure hostname and rebar uuid!"
+    sleep 9000
+    exit 1
+fi
 if [ -f /etc/sysconfig/network ] ; then
       sed -i -e "s/HOSTNAME=.*/HOSTNAME=${HOSTNAME}/" /etc/sysconfig/network
 fi
 echo "${HOSTNAME#*.}" >/etc/domainname
 echo "$HOSTNAME" >/etc/hostname
 hostname "$HOSTNAME"
+export HOSTNAME
 
+echo "$REBAR_UUID" > /etc/rebar-uuid
 update-rc.d rebar_join defaults
-rebar nodes update "$HOSTNAME" '{"bootenv": "local"}'
-while [[ $(rebar nodes get "$HOSTNAME" attrib provisioner-active-bootstate |jq -r '.value') != local ]]; do
+rebar nodes update "$REBAR_UUID" '{"bootenv": "local"}'
+while [[ $(rebar nodes get "$REBAR_UUID" attrib provisioner-active-bootstate |jq -r '.value') != local ]]; do
     sleep 1
 done
 EOF
